### ISSUE TITLE
Feedback review Page

### ISSUE THREAD

**Issue by iampava** [FrontEnd-ro/frontend.ro#12]
First time feedback-givers will need to pass a review process intended to keep the quality of the platform as high as possible.

The flow is like this:

1. A `user` submits an exercise
2. A first-time `contributor` views that exercise in the dashboard
3. The `contributor` gives feedback to the exercise
4. An `admin` is notified of this feedback
5. The `admin` reviews the feedback
6. If there are any adjustments to be made, the `admin` and the `contributor` discuss on the feedback
7. When the feedback is accepted, it gets sent to the actual `user` that solved the exercise

We need to create a separate page/route for the feedback review process:

1. Only an admin can go on that page
2. The page should show the exercise description + the user's code (let's mock them for now with some lorem-ipsum and a textarea)
3. Admin should see all the feedbacks (you can give multiple feedbacks, each on a separate portion of the code)
4. Admin can mark each individual feedback as approved/rejected or have an option to approve all.
    * He can also comment on each feedback to explain what needs to be changed
5. After all the feedbacks have been marked, he can submit his remarks
    * if everything is ok, the feedback will get sent to the end user
    * if there are changes required, the contributor will get notified, see them, and of course comment or make changes to the feedback. This keeps going until everything is ok!

**Comment by catalinpopusoi** [comment]
I'll work on this one. Will update the issue with a PR when it's done.

**Comment by catalinpopusoi** [comment]
I've raised a draft PR here: #20 
This is still WIP, so the issue should not be closed yet.

**Comment by iampava** [comment]
Done
