### ISSUE TITLE
Translate timeline for submitted exercises and redirect user to his profile

### ISSUE THREAD

**Issue by andreeatoma** [FrontEnd-ro/frontend.ro#134]
- the timeline should be translated in romanian (something like "trimis acum o ora")
- clicking the username, redirects the user to http://localhost:3000/iampava

![feedback](https://user-images.githubusercontent.com/18526942/112849283-934f7000-90b1-11eb-926c-35f606f230d0.png)

**Comment by andreeatoma** [comment]
I renamed and translated the time elapsed since last submission and redirected the user to his profile. Here I did some tests.

![2](https://user-images.githubusercontent.com/18526942/112965456-f2fd5800-9151-11eb-8fd9-86800ed2cc8d.png)
![3](https://user-images.githubusercontent.com/18526942/112965473-f690df00-9151-11eb-80db-ea0f0c103358.png)
![4](https://user-images.githubusercontent.com/18526942/112965488-fabcfc80-9151-11eb-82de-d5fa932f37c9.png)

**Comment by iampava** [comment]
Merged in https://github.com/FrontEnd-ro/frontend.ro/commit/547332147361906a568d5f53667d63d25af1e03b

Closing
