### ISSUE TITLE
Integrate Monaco Editor for code submission

### ISSUE THREAD

**Issue by iampava** [FrontEnd-ro/frontend.ro#14]
I propose we use Monaco Editor (the open source editor behind VSCode) - for the code submissions. I already have this implemented in https://DevDrive.io - so I think we can reuse a lot of this code.

We will NOT run the code inside the app. This is not the point of this platform, and I don't want us to waste time on this as there are a lot of options that specialize on this. 

People will just submit it using the Monaco Editor, and the contributors will give feedback by running locally or on a third-party app designed for this: CodePen, CodeSandbox, etc... The editor must support folders as well, which is implemented in DevDrive soooo more code reuse.

**Comment by stefanhagiu** [comment]
Why not embed CodePen (https://blog.codepen.io/2019/09/03/react-codepen-prefill-embeds/) or CodeSandbox etc. into the page itself. This way while working on lectures, homework or projects people can also create a tiny portfolio. Also I think it will help them to actually see what they are building, it makes it more appealing, I think, to be able to see the result of your code while you write it down.

**Comment by iampava** [comment]
The only problem with this is giving feedback on the code. I think an experience similar to GitHub PR's is a must have and with these embeds I don't see it possible.

However, I researched a while back and IT IS POSSIBLE to have a mix and maybe "the best of both worlds". Instead of copy-pasting the code, the user will submit a CodePen/CodeSandbox link. We'll crawl that link and fetch the code into our DB so that the contributor/teacher can give the feedback as intended. Then, the user will see the feedback in the Monaco Editor, but make the changes on CodePen/Codesandbox and re-submit the link.

What do you think of this approach?

**Comment by stefanhagiu** [comment]
Think this could work as long as we mitigate the pain and tie the feedback link to the CodPen link so he can access fast both the feedback and the playground.

**Comment by iampava** [comment]
Done
