### ISSUE TITLE
Have a dedicated page with useful resources

### ISSUE THREAD

**Issue by iampava** [FrontEnd-ro/frontend.ro#155]
There are a lot of useful tools/websites out there. From getting free stuff like Images (https://Unplash.com) to getting icons: https://FontAwesome.com,creating a UI library to keep track within your team - https://storybook.js.org/ or coding online: https://codepen.io or https://codesandbox.io

Maybe we should create a dedicated page with those kind of resources validated by us, and categorized in some way

**Comment by dirzun** [comment]
HTML
https://htmlreference.io/

CSS
https://cssreference.io/

https://yoksel.github.io/flex-cheatsheet/
https://cssflex-generator.netlify.app/
https://flexbox.malven.co/


https://yoksel.github.io/grid-cheatsheet/
https://cssgrid-generator.netlify.app/
https://grid.malven.co/

Colors
https://uigradients.com/
https://coolors.co/
https://www.eggradients.com/

UI
https://material.io/design
https://ant.design/

Images
https://www.flaticon.com/
https://pixabay.com/
https://unsplash.com/

**Comment by iampava** [comment]
Done!
