### ISSUE TITLE
Extract formatted text into a separate component

### ISSUE THREAD

**Issue by iampava** [FrontEnd-ro/frontend.ro#232]
Right now if we want to inline some piece of code we're using the `formatted` class:

`<span className="formatted"> type="" </span>`
![image](https://user-images.githubusercontent.com/11327761/125162853-d631e100-e192-11eb-895e-653287aadbd4.png)

Let's extract into a separate component so we don't have to write this class over and over again.

Make sure the component has an `as` prop in case we want to render it as a different element (eg: `<p>`, `<strong>`, etc)

**Comment by swarup4741** [comment]
```jsx
export default function Formatted(props) {
  return (
    <>
      <props.as>{props.children}</props.as>
    </>
  );
}
```

Do you want something like this ?

**Comment by iampava** [comment]
Yes, but I think it should also be a `forwardRef` component, so we can apply normal HTML attributes to it, like [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#title_attribute_inheritance):

```
<Formatted as="p" title="Greeting">  Hello, I am bob! </Formatted>
```

**Comment by swarup4741** [comment]
```jsx
export default function Formatted(props) {
  return (
    <>
      <props.as {...props} className="formatted">{props.children}</props.as>
    </>
  );
}
```
just destructuring the props will do the work i hope ...

**Comment by iampava** [comment]
Yes, I think you might be right.

We're using TS so ideally we would have types. For instance, in you example, since you used `as="a"`, it would be great to get suggestions for the correct props: `href`, `target`, just like when using the normal `<a>` element.

![image](https://user-images.githubusercontent.com/11327761/125195231-7b18f080-e25d-11eb-8982-0ac5ae4e5c75.png)

I found this thread in case it might help: https://stackoverflow.com/questions/55969769/typing-a-dynamic-tag-in-react-with-typescript

<hr>

PS: I've assigned you. Thanks :D

**Comment by swarup4741** [comment]
Thank you so much for the guide !!  😊

**Comment by iampava** [comment]
No worries :D 

You'll probably get some errors when trying to run the project, will try and fix that in the following days. Until then, I think to test you can just run `yarn build` and verify that the build is created.

**Comment by swarup4741** [comment]
Do i need to install exactly node `v 16.1.0` ?  It is showing me this error ....

<img width="786" alt="frontend" src="https://user-images.githubusercontent.com/69234404/125207227-bc82bd80-e2a8-11eb-8964-aaa511211c5b.PNG">

**Comment by iampava** [comment]
Yep. I think easier it would be to change this line `"node": "16.1.0"` to your version. Then before you create the PR just revert back that line. 

It should work. 

In the meantime I added this issue: https://github.com/FrontEnd-ro/frontend.ro/issues/234. I think it should allow everyone with a `16+` version

**Comment by swarup4741** [comment]
I have created the component and also separated the `scss` file and its working fine. Also replacing all the `className="formatted"` lines with the Component throughout the whole project

**Comment by iampava** [comment]
Great! I think you can open a Pull Request then.

**Comment by iampava** [comment]
I forgot to update our CONTIBUTING.md file but lately we've been adding the issue inside the commit message (in parantheses `()`)

![image](https://user-images.githubusercontent.com/11327761/125250518-039b9d80-e2ff-11eb-91c5-ad1888f2af29.png)

**Comment by swarup4741** [comment]
<img width="405" alt="error" src="https://user-images.githubusercontent.com/69234404/125349640-6b8fc980-e37b-11eb-803e-d7803db2acde.PNG">I

'm getting only this error all over code while running `yarn build`
Should I ignore this ?

**Comment by iampava** [comment]
I think you can safely ignore it, yep. It might be actually a problem with my config...

**Comment by swarup4741** [comment]
Not a problem at all. I have adjusted my settings according to your config
