### ISSUE TITLE
Lesson page crashes with unknown bug

### ISSUE THREAD

**Issue by iampava** [FrontEnd-ro/frontend.ro#298]
![image](https://user-images.githubusercontent.com/11327761/131008018-a6a13b24-6c82-4157-93c6-d323b00463bb.png)

Lesson: https://frontend.ro/html/liste#tipuri-de-liste
Browser: Firefox Nightly

Doesn't reproduce every time 🤷‍♂️

**Comment by lazarnarcis** [comment]
i really don't have this error @iampava !

**Comment by iampava** [comment]
It doesn't happen every time 🤷‍♂️
