### ISSUE TITLE
Contributors accounts from README.me open in a new tab

### ISSUE THREAD

**Issue by lazarnarcis** [FrontEnd-ro/frontend.ro#463]
![Screenshot 2021-11-30 200118](https://user-images.githubusercontent.com/82839799/144102405-5f3904c5-d98f-4f7b-b0ce-622327c74c93.png)
I mean the links of these users, what do you say?

**Comment by iampava** [comment]
I don't think it matters. I see other projects open it in the same tab: https://github.com/vuejs/vue - so let's leave it like this. Not worth the time
