### ISSUE TITLE
Follow the user

### ISSUE THREAD

**Issue by lazarnarcis** [FrontEnd-ro/frontend.ro#468]
Add the "Follow" button and the number of users that user is following.
![Screenshot 2021-12-03 202642](https://user-images.githubusercontent.com/82839799/144653939-837bf9b5-fb7d-49f9-a057-eccb98e702d3.png)
That's a good idea, isn't it?

**Comment by iampava** [comment]
You mean a follow functionality between users?

**Comment by lazarnarcis** [comment]
yes :D

**Comment by iampava** [comment]
Drop it. We won't do this in the future, don't want to transform it into a social network
