### ISSUE TITLE
Realign the password reset button

### ISSUE THREAD

**Issue by lazarnarcis** [FrontEnd-ro/frontend.ro#497]

**Comment by iampava** [comment]
Can you add a photo please? I'm not sure I understand the issue

**Comment by lazarnarcis** [comment]
![Screenshot 2022-01-02 113911](https://user-images.githubusercontent.com/82839799/147871964-5709de83-744f-47e9-85c1-373c62719f99.png)

**Comment by lazarnarcis** [comment]
look at the link "Ai uitat parola?"

**Comment by iampava** [comment]
Done!
