### ISSUE TITLE
Amend existing pathnames in the URLs

### ISSUE THREAD

**Issue by nmaties** [FrontEnd-ro/frontend.ro#61]
Amend every existing pathname to be written in Romanian language plus the words to separated using `kebab-case`, for example:

`/html/images` -> it should be `/html/imagini`
`/html/learn` -> it should be `/html/invata`
`/html/imagesWithDescriptions` -> should be `/html/imagini-cu-descrieri`

All the pathnames should follow these rules:

1. To be written in Romanian language
2. To contain all the words from the title page ( if the title page is too long, at least 5-6 words)
3. The words to be `kebab-case` written

PS: When reviewing a PR please take into consideration this.

**Comment by iampava** [comment]
Done: https://github.com/FrontEnd-ro/frontend.ro/commit/1d4bd50d270925ba3c19d9ce6e470f78a5bf2387
