### ISSUE TITLE
Issue on "IMAGINI" section on mobile devices

### ISSUE THREAD

**Issue by razvanonweb** [FrontEnd-ro/frontend.ro#75]
When u refresh the main page and try to open the "imagini" section,  will appear 3 different videos, istead of section about img

Here it's a video to see the problem or an alternative link to see it : 

https://user-images.githubusercontent.com/69815253/105482606-46b27780-5cb1-11eb-91cb-0f5d0b0ada3a.mp4

https://imgur.com/gallery/4FGN9Lb

**Comment by iampava** [comment]
@razvanonweb  thanks for submitting this issue. Can you confirm whether or not the bug is still replicating?

**Comment by iampava** [comment]
closing, was fixed
